spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행.

  datasource:
    url: jdbc:h2:mem:tdd
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

level:
  org.springframework.transaction.interceptor: TRACE
  org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
  org.springframework.orm.jpa.JpaTransactionManager: DEBUG
  org.hibernate.resource.transaction: DEBUG
  org.hibernate.SQL: DEBUG